routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('stok','stokController');

app/Stok.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stok extends Model
{
    protected $fillabel = ['nama_barang', 'jenis_barang', 'jml_stok', 'supplier', 'harga_satuan', 'harga_total', 'keterangan', 'tanggal'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/stokController.php
<?php

namespace App\Http\Controllers;
use App\Stok;
use Illuminate\Http\Request;


class stokController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $stok = Stok::all();
        return view('admin.main', compact('stok'));
        // return view('admin/main');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $stok = new Stok();
        $stok->nama_barang = request('nama_barang');
        $stok->jenis_barang = request('jenis_barang');
        $stok->jml_stok = request('jml_stok');
        $stok->supplier = request('supplier');
        $stok->harga_satuan = request('harga_satuan');
        $stok->harga_total = request('harga_total');
        $stok->keterangan = request('keterangan');
        $stok->tanggal = request('tanggal');
        $stok->save();

        return redirect('stok')->with('success','stok sudah ditambahkan ke database');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $stok = Stok::findOrFail($id);
         return view('admin.edit',compact('stok'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $stok = Stok::findOrFail($id);
        $stok->nama_barang = request('nama_barang');
        $stok->jenis_barang = request('jenis_barang');
        $stok->jml_stok = request('jml_stok');
        $stok->supplier = request('supplier');
        $stok->harga_satuan = request('harga_satuan');
        $stok->harga_total = request('harga_total');
        $stok->keterangan = request('keterangan');
        $stok->tanggal = request('tanggal');
        $stok->save();
        return redirect('stok')->with('success','database stok telah berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $stok = Stok::findOrFail($id);
        $stok->delete();

        return redirect('stok')->with('success', 'data stok is successfully deleted');
    }
}

resources/views/admin/edit.blade.php
 @extends('adminlte::page')

@section('title', 'Edit')

@section('content_header')
    <h1>Ubah Data</h1>
@stop

@section('content')
        <span>Ubah Data <strong>STOK</strong></span>
    <hr>
    <form action="/stok/{{$stok->id}}" method="POST">
    	@csrf
        @method('PATCH')
    	<div class="form-group">
            <label for="nama_barang">Nama Barang<label>
    <input type="text" class="form-control" name="nama_barang" value="{{$stok->nama_barang}}"/>
        </div>
        <div class="form-group">
            <label for="jenis_barang">Merk Barang<label>
            <input type="text" class="form-control" name="jenis_barang" value="{{$stok->jenis_barang}}"/>
        </div>
        <div class="form-group">
            <label for="jml_stok">Jumlah Stok</label>
            <input type="text" class="form-control" name="jml_stok" value="{{$stok->jml_stok}}"/>
        </div>
        <div class="form-group">
            <label for="supplier">Nama Supplier</label>
            <input type="text" class="form-control" name="supplier" value="{{$stok->supplier}}"/>
        </div>
        <div class="form-group">
            <label for="harga_satuan">Harga Satuan Barang</label>
            <input type="text" class="form-control" name="harga_satuan" value="{{$stok->harga_satuan}}"/>
        </div>
        <div class="form-group">
            <label for="harga_total">Harga Total</label>
            <input type="text" class="form-control" name="harga_total" value="{{$stok->harga_total}}"/>
        </div>
        <div class="form-group">
            <label for="keterangan">Keterangan</label>
            <input type="text" class="form-control" name="keterangan" value="{{$stok->keterangan}}"/>
        </div>
        <div class="form-group">
            <label for="tanggal">tanggal input</label>
            <input type="date" class="form-control" name="tanggal" value="{{$stok->tanggal}}" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/main.blade.php
 @extends('adminlte::page')

@section('title', 'Stok material')

@section('content_header')
    <h1>Halaman Stok</h1>
@stop

@section('content')
    <div class="card show col-md-12">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold">Data Stok Material</h6>
	</div>
	<div class="card-body">
		<a href="{{ route('stok.create') }}" class="btn btn-sm btn-danger" style="float: right;">Tambah</a>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>No.</th>
					<th>Nama barang</th>
					<th>Merk Barang</th>
					<th>Jumlah Barang</th>
					<th>Harga Satuan</th>
					<th>Harga Total</th>
					<th>Keterangan</th>
					<th>Tanggal</th>
					<th>Nama Supplier</th>
					<th>Aksi</th>
				</tr>
			</thead>
			<tbody>
				@foreach ($stok as $stoks)
				<tr>
					<td>{{$stoks->id}}</td>
					<td>{{$stoks->nama_barang}}</td>
					<td>{{$stoks->jenis_barang}}</td>
					<td>{{$stoks->jml_stok}}</td>
					<td>{{number_format($stoks->harga_satuan, 2, ',', '.')}}</td>
					<td>{{number_format($stoks->harga_total, 2, ',', '.')}}</td>
					<td>{{$stoks->keterangan}}</td>
					<td>{{$stoks->tanggal}}</td>
					<td>{{$stoks->supplier}}</td>
					<td>
						<a href="{{ route('stok.edit',$stoks->id)}}" class="btn btn-primary">Edit</a>
                      <form action="{{ route('stok.destroy', $stoks->id)}}" method="post">
                        @csrf
                          @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                		</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/tambah.blade.php
 @extends('adminlte::page')

@section('title', 'Tambah')

@section('content_header')
    <h1>Tambah Data</h1>
@stop

@section('content')
        <span>Tambah <strong>STOK</strong></span>
    <hr>
    <form action="{{ route('stok.store') }}" method="POST">
    	@csrf
    	<div class="form-group">
            <label for="nama_barang">Nama Barang<label>
            <input type="text" class="form-control" name="nama_barang"/>
        </div>
        <div class="form-group">
            <label for="jenis_barang">Merk Barang<label>
            <input type="text" class="form-control" name="jenis_barang"/>
        </div>
        <div class="form-group">
            <label for="jml_stok">Jumlah Stok</label>
            <input type="text" class="form-control" name="jml_stok"/>
        </div>
        <div class="form-group">
            <label for="supplier">Nama Supplier</label>
            <input type="text" class="form-control" name="supplier"/>
        </div>
        <div class="form-group">
            <label for="harga_satuan">Harga Satuan Barang</label>
            <input type="text" class="form-control" name="harga_satuan"/>
        </div>
        <div class="form-group">
            <label for="harga_total">Harga Total</label>
            <input type="text" class="form-control" name="harga_total"/>
        </div>
        <div class="form-group">
            <label for="keterangan">Keterangan</label>
            <input type="text" class="form-control" name="keterangan"/>
        </div>
        <div class="form-group">
            <label for="tanggal">tanggal input</label>
            <input type="date" class="form-control" name="tanggal"/>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/home.blade.php
 @extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>